# Generated by Django 5.1.3 on 2024-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_review_novel_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.CharField(choices=[('popular', 'Popular'), ('latest', 'Latest'), ('new', 'New'), ('featured', 'Featured')], default='popular', max_length=20),
        ),
    ]
