# Generated by Django 5.1.3 on 2024-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_novel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novel',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
