# Generated by Django 5.1.3 on 2024-11-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_novel_is_featured_novel_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='is_popular',
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.CharField(choices=[('popular', 'Popular'), ('latest', 'Latest'), ('completed', 'Completed'), ('featured', 'Featured')], default='popular', max_length=20),
        ),
    ]
