# Generated by Django 5.1.3 on 2024-11-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_review_content_remove_review_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
